.gitignore, pom.xml, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java, src/main/resources/META-INF/resources/frontend/styles/multiselect-cb-hide.css, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/DemoView.java
=> Added select row on click feature

src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java
=> Allow setting a fixed height

src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java
=> Avoid code duplication (#25)

src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java
See https://sonarcloud.io/project/issues?id=FlowingCode_TwinColGridAddon
=> Code cleanup

pom.xml, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/test/SerializationTest.java
=> Added serialization test

src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java
=> Added flag to check if drop items event ocurred inside a grid

src/test/java/com/flowingcode/vaadin/addons/twincolgrid/BoundDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/DragAndDropDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/FilterableDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/TwincolDemoView.java
Code sroll css
Renamed demo classes
=> Added split layout with source code. Can be toggled with checkbox.

pom.xml, src/test/java/com/flowingcode/vaadin/addons/DemoLayout.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/DemoView.java
Add an empty DemoLayout for integration with the demo site
=> Add DemoLayout

src/test/java/com/flowingcode/vaadin/addons/twincolgrid/TwincolDemoView.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/test/LayoutTest.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/test/SerializationTest.java, src/test/resources/META-INF/resources/frontend/styles/demo-styles.css
Add LayoutTest and fix obj parameter not being used in SerializationTest
=> Demo layout

src/test/java/com/flowingcode/vaadin/addons/twincolgrid/TwincolDemoView.java
Resolves [https://github.com/FlowingCode/AddonsDemoV14/issues/21](https://github.com/FlowingCode/AddonsDemoV14/issues/21)
=> Tabs reordered

src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java
Fixes [https://github.com/FlowingCode/TwinColGridAddon/issues/53](https://github.com/FlowingCode/TwinColGridAddon/issues/53)
=> Drag and drop fixed

pom.xml, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/TwincolDemoView.java
https://github.com/FlowingCode/AddonsDemoV14/issues/31
=> Update commons-demo dependency to 2.1.0-SNAPSHOT

src/test/java/com/flowingcode/vaadin/addons/twincolgrid/TwincolDemoView.java
https://github.com/FlowingCode/AddonsDemoV14/issues/31
=> Make demo view extend TabbedDemo instead of VerticalLayout

src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java
❗ First apply PR #67 ❗ 
Close #70
=> Provide an overload of addSortableColumn that sets the column key

.gitignore, pom.xml, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGridListAdapter.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/BoundDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/DragAndDropDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/FilterableDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/Library.java
+refactor demo code for legibility
+return empty set in getEmptyValue
=> feat: extend selection semantics to support ordered value along with UI to adjust

pom.xml, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java, src/main/resources/META-INF/resources/frontend/styles/twin-col-grid-button.css, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/BoundDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/DragAndDropDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/FilterableDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/TwincolDemoView.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/VerticalOrientationDemo.java
Fix for #82. 
Demo refactor to use new commons-demo version with annotations.
=> Add support to set orientation

src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/DoubleClickDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/TwincolDemoView.java
=> feat: move items by doubleclick

pom.xml, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/FilterableTwinColumn.java, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/LegacyTwinColGrid.java, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGridListAdapter.java, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColumn.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/BoundDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/DoubleClickDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/DragAndDropDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/FilterableDemo.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/OrientationDemo.java
Close #116 and #108 and address https://github.com/FlowingCode/TwinColGridAddon/pull/110#issuecomment-1305701671
(Merged into a temporary branch `v3.0.0` because we need to sort out a couple of things before releasing 3.0.0)
=> Version 3 refactor

src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java
=> fix: fix filterable column display

src/test/java/com/flowingcode/vaadin/addons/twincolgrid/OrientationDemo.java
=> fix(demo): avoid use of deprecated constructor

pom.xml
=> [v2.x] build: attach sources and javadoc in package phase 

pom.xml
=> [2.x] build: restore original name

src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java
=> fix: fix button position when orientation changes

src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java
=> [2.x] fix: fix button position when orientation changes 

pom.xml, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/DragAndDropDemo.java
Close #159 (and other related occurrences)
=> Associate Label with components

pom.xml, src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java, src/test/java/com/flowingcode/vaadin/addons/twincolgrid/DragAndDropDemo.java
=> [2.x] Associate Label with components

pom.xml
=> [2.x] Make vaadin dependency optional and add profiles for snapshot versions
